/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UiSystemImport } from './routes/ui-system'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index.route'
import { Route as AuthMyAccountImport } from './routes/_auth.my-account'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthTournamentsTournamentIdLayoutImport } from './routes/_auth.tournaments/$tournamentId/_layout'

// Create Virtual Routes

const AuthTournamentsTournamentIdImport = createFileRoute(
  '/_auth/tournaments/$tournamentId',
)()
const AuthTournamentsIndexLazyImport = createFileRoute('/_auth/tournaments/')()
const AuthLeaguesIndexLazyImport = createFileRoute('/_auth/leagues/')()
const AuthLeaguesLeagueIdLazyImport = createFileRoute(
  '/_auth/leagues/$leagueId',
)()
const AuthTournamentsTournamentIdLayoutStandingsLazyImport = createFileRoute(
  '/_auth/tournaments/$tournamentId/_layout/standings',
)()
const AuthTournamentsTournamentIdLayoutSimulatorLazyImport = createFileRoute(
  '/_auth/tournaments/$tournamentId/_layout/simulator',
)()
const AuthTournamentsTournamentIdLayoutRankingLazyImport = createFileRoute(
  '/_auth/tournaments/$tournamentId/_layout/ranking',
)()
const AuthTournamentsTournamentIdLayoutMatchesLazyImport = createFileRoute(
  '/_auth/tournaments/$tournamentId/_layout/matches',
)()

// Create/Update Routes

const UiSystemRoute = UiSystemImport.update({
  path: '/ui-system',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthMyAccountRoute = AuthMyAccountImport.update({
  path: '/my-account',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTournamentsTournamentIdRoute =
  AuthTournamentsTournamentIdImport.update({
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthTournamentsIndexLazyRoute = AuthTournamentsIndexLazyImport.update({
  path: '/tournaments/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.tournaments/index.lazy').then((d) => d.Route),
)

const AuthLeaguesIndexLazyRoute = AuthLeaguesIndexLazyImport.update({
  path: '/leagues/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.leagues/index.lazy').then((d) => d.Route),
)

const AuthLeaguesLeagueIdLazyRoute = AuthLeaguesLeagueIdLazyImport.update({
  path: '/leagues/$leagueId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.leagues/$leagueId.lazy').then((d) => d.Route),
)

const AuthTournamentsTournamentIdLayoutRoute =
  AuthTournamentsTournamentIdLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthTournamentsTournamentIdRoute,
  } as any)

const AuthTournamentsTournamentIdLayoutStandingsLazyRoute =
  AuthTournamentsTournamentIdLayoutStandingsLazyImport.update({
    path: '/standings',
    getParentRoute: () => AuthTournamentsTournamentIdLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth.tournaments/$tournamentId/_layout.standings.lazy'
    ).then((d) => d.Route),
  )

const AuthTournamentsTournamentIdLayoutSimulatorLazyRoute =
  AuthTournamentsTournamentIdLayoutSimulatorLazyImport.update({
    path: '/simulator',
    getParentRoute: () => AuthTournamentsTournamentIdLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth.tournaments/$tournamentId/_layout.simulator.lazy'
    ).then((d) => d.Route),
  )

const AuthTournamentsTournamentIdLayoutRankingLazyRoute =
  AuthTournamentsTournamentIdLayoutRankingLazyImport.update({
    path: '/ranking',
    getParentRoute: () => AuthTournamentsTournamentIdLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth.tournaments/$tournamentId/_layout.ranking.lazy'
    ).then((d) => d.Route),
  )

const AuthTournamentsTournamentIdLayoutMatchesLazyRoute =
  AuthTournamentsTournamentIdLayoutMatchesLazyImport.update({
    path: '/matches',
    getParentRoute: () => AuthTournamentsTournamentIdLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth.tournaments/$tournamentId/_layout.matches.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/ui-system': {
      id: '/ui-system'
      path: '/ui-system'
      fullPath: '/ui-system'
      preLoaderRoute: typeof UiSystemImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/my-account': {
      id: '/_auth/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof AuthMyAccountImport
      parentRoute: typeof AuthImport
    }
    '/_auth/leagues/$leagueId': {
      id: '/_auth/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthLeaguesLeagueIdLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/leagues/': {
      id: '/_auth/leagues/'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AuthLeaguesIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/tournaments/': {
      id: '/_auth/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthTournamentsIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/tournaments/$tournamentId': {
      id: '/_auth/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof AuthTournamentsTournamentIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/tournaments/$tournamentId/_layout': {
      id: '/_auth/tournaments/$tournamentId/_layout'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof AuthTournamentsTournamentIdLayoutImport
      parentRoute: typeof AuthTournamentsTournamentIdRoute
    }
    '/_auth/tournaments/$tournamentId/_layout/matches': {
      id: '/_auth/tournaments/$tournamentId/_layout/matches'
      path: '/matches'
      fullPath: '/tournaments/$tournamentId/matches'
      preLoaderRoute: typeof AuthTournamentsTournamentIdLayoutMatchesLazyImport
      parentRoute: typeof AuthTournamentsTournamentIdLayoutImport
    }
    '/_auth/tournaments/$tournamentId/_layout/ranking': {
      id: '/_auth/tournaments/$tournamentId/_layout/ranking'
      path: '/ranking'
      fullPath: '/tournaments/$tournamentId/ranking'
      preLoaderRoute: typeof AuthTournamentsTournamentIdLayoutRankingLazyImport
      parentRoute: typeof AuthTournamentsTournamentIdLayoutImport
    }
    '/_auth/tournaments/$tournamentId/_layout/simulator': {
      id: '/_auth/tournaments/$tournamentId/_layout/simulator'
      path: '/simulator'
      fullPath: '/tournaments/$tournamentId/simulator'
      preLoaderRoute: typeof AuthTournamentsTournamentIdLayoutSimulatorLazyImport
      parentRoute: typeof AuthTournamentsTournamentIdLayoutImport
    }
    '/_auth/tournaments/$tournamentId/_layout/standings': {
      id: '/_auth/tournaments/$tournamentId/_layout/standings'
      path: '/standings'
      fullPath: '/tournaments/$tournamentId/standings'
      preLoaderRoute: typeof AuthTournamentsTournamentIdLayoutStandingsLazyImport
      parentRoute: typeof AuthTournamentsTournamentIdLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthDashboardRoute,
    AuthMyAccountRoute,
    AuthLeaguesLeagueIdLazyRoute,
    AuthLeaguesIndexLazyRoute,
    AuthTournamentsIndexLazyRoute,
    AuthTournamentsTournamentIdRoute:
      AuthTournamentsTournamentIdRoute.addChildren({
        AuthTournamentsTournamentIdLayoutRoute:
          AuthTournamentsTournamentIdLayoutRoute.addChildren({
            AuthTournamentsTournamentIdLayoutMatchesLazyRoute,
            AuthTournamentsTournamentIdLayoutRankingLazyRoute,
            AuthTournamentsTournamentIdLayoutSimulatorLazyRoute,
            AuthTournamentsTournamentIdLayoutStandingsLazyRoute,
          }),
      }),
  }),
  LoginRoute,
  UiSystemRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/ui-system"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/my-account",
        "/_auth/leagues/$leagueId",
        "/_auth/leagues/",
        "/_auth/tournaments/",
        "/_auth/tournaments/$tournamentId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/ui-system": {
      "filePath": "ui-system.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/my-account": {
      "filePath": "_auth.my-account.tsx",
      "parent": "/_auth"
    },
    "/_auth/leagues/$leagueId": {
      "filePath": "_auth.leagues/$leagueId.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/leagues/": {
      "filePath": "_auth.leagues/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/tournaments/": {
      "filePath": "_auth.tournaments/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/tournaments/$tournamentId": {
      "filePath": "_auth.tournaments/$tournamentId",
      "parent": "/_auth",
      "children": [
        "/_auth/tournaments/$tournamentId/_layout"
      ]
    },
    "/_auth/tournaments/$tournamentId/_layout": {
      "filePath": "_auth.tournaments/$tournamentId/_layout.tsx",
      "parent": "/_auth/tournaments/$tournamentId",
      "children": [
        "/_auth/tournaments/$tournamentId/_layout/matches",
        "/_auth/tournaments/$tournamentId/_layout/ranking",
        "/_auth/tournaments/$tournamentId/_layout/simulator",
        "/_auth/tournaments/$tournamentId/_layout/standings"
      ]
    },
    "/_auth/tournaments/$tournamentId/_layout/matches": {
      "filePath": "_auth.tournaments/$tournamentId/_layout.matches.lazy.tsx",
      "parent": "/_auth/tournaments/$tournamentId/_layout"
    },
    "/_auth/tournaments/$tournamentId/_layout/ranking": {
      "filePath": "_auth.tournaments/$tournamentId/_layout.ranking.lazy.tsx",
      "parent": "/_auth/tournaments/$tournamentId/_layout"
    },
    "/_auth/tournaments/$tournamentId/_layout/simulator": {
      "filePath": "_auth.tournaments/$tournamentId/_layout.simulator.lazy.tsx",
      "parent": "/_auth/tournaments/$tournamentId/_layout"
    },
    "/_auth/tournaments/$tournamentId/_layout/standings": {
      "filePath": "_auth.tournaments/$tournamentId/_layout.standings.lazy.tsx",
      "parent": "/_auth/tournaments/$tournamentId/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
