name: Caching dependencies
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Install dependencies of the Application
        run: yarn

      - name: Build the Application
        run: yarn build
