name: Deploy
on:
  workflow_call:
    inputs:
      env_name:
        description: "environment name"
        default: "production"
        type: string
        required: true
env:
  AWS_BUCKET_ID: ${{secrets.AWS_BUCKET_ID}}
  ENVIRONMENT: ${{ inputs.env_name }}

jobs:
  deploy:
    environment: ${{ inputs.env_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site
        run: aws s3 sync ./dist s3://${AWS_BUCKET_ID}
      - name: Build the Application
        run: echo "env => $ENVIRONMENT"
