name: Environment Variables and Secrets
on:
  push:
    branches:
      - chore/**
env:
  MY_ENV_VAR: ${{ github.MY_SECRET }}
  MY_SECRET: ${{ secrets.MY_SECRET }}
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Running an NPM script command
        run: yarn test:$MY_ENV_VAR
  job_two:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Running an NPM script command
        run: yarn test:$MY_SECRET
