name: Reusable Flow Main
on:
  push:
    branches:
      - chore/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      - name: Build the Application
        run: yarn build
