name: Matrix
on:
  push:
    branches:
      - chore/**
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12.x, 14.x, 18.x]
        node-operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.node-operating-system }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build the Application
        run: yarn build
