name: Multiple Jobs - Sequential
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Checking node version
        run: node --version

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checking node version
        run: node --version

      - name: Install dependencies
        run: yarn install
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Checking node version
        run: node --version
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Checking node version
        run: node --version

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checking node version
        run: node --version

      - name: Install dependencies
        run: yarn install
  fourth-job:
    needs: [second-job, third-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Checking node version
        run: node --version
