name: Reusable Flow Main
on:
  push:
    branches:
      - poc/gh-actions-**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Create a folder
        run: mkdir dist

      - name: Create a file in the folder
        run: echo "Earth is ${{ secrets.EARTH_FORMAT }}!!!!!" > dist/hello.txt

      - name: Upload fake result
        uses: actions/upload-artifact@v4
        with:
          name: build-output-folder
          path: dist
  deploy-usable:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact_name: mario-brothers
    secrets:
      EARTH_FORMAT: "${{ secrets.EARTH_FORMAT }}" ## The most important part is to put the secret in double quotes
  deploy-result:
    needs: deploy-usable
    runs-on: ubuntu-latest
    steps:
      - name: Just print the output of a reusable workflow_call
        run: echo "The job id is ${{ needs.deploy-usable.outputs.deploy-result }}"
