name: Storing and Using Outputs
on:
  push:
    branches:
      - main
jobs:
  fake_build:
    runs-on: ubuntu-latest
    outputs:
      firstname: ${{ steps.firstname.outputs.firstname }}
      lastname: ${{ steps.lastname.outputs.lastname }}
    steps:
      - name: Create a folder
        run: mkdir dist

      - name: Create an output value for firstname
        id: firstname
        run: echo "firstname=mario" >> "$GITHUB_OUTPUT"

      - name: Create an output value for lastname
        id: lastname
        run: echo "lastname=brusarosco" >> "$GITHUB_OUTPUT"
  fake_publish:
    runs-on: ubuntu-latest
    needs: fake_build
    steps:
      - env:
          OUTPUT1: ${{ needs.fake_build.outputs.firstname }}
          OUTPUT2: ${{ needs.fake_build.outputs.lastname }}
        run: echo "$OUTPUT1 $OUTPUT2"
      - name: Logging
        run: echo "${{ toJson(needs.fake_build.outputs) }}"
